In [1]:
import numpy as np 

# Create an array of 10 zeros
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
# Create an array of all the even integers from 10 to 50.
even_integers = np.arange(10, 51, 2)
print("even integers from 10 to 50:" , even_integers)

even integers from 10 to 50: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [3]:
# Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values from 0 to 8:\n", matrix_3x3)

3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Use NumPy to generate a matrix (5x4) consisting of 20 random integers
random_matrix = np.random.randint(0, 100, (5, 4))
print("5x4 matrix with 20 random integers:\n", random_matrix)

5x4 matrix with 20 random integers:
 [[92 61 40 19]
 [96 14 25  4]
 [58  9 69 96]
 [42 88 37 52]
 [33 67 19 42]]


In [6]:
# Create an array of 20 linearly spaced points between 0 and 1
linear_spaced_array = np.linspace(0, 1, 20)
print("Array of 20 linearly spaced points between 0 and 1:", linear_spaced_array)

Array of 20 linearly spaced points between 0 and 1: [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [7]:
import numpy as np 

# Write code that slices the matrix below (items in red only)
matrix = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])
sliced_matrix = matrix[2:, 1:]
print(sliced_matrix)
                   

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [8]:
import numpy as np
# Write code that slices the matrix below (items in red only)
matrix = np.array([[ 1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])
elements = [matrix[0, 1], matrix[1, 1], matrix[2, 1]]
print(elements)

[2, 7, 12]


In [9]:
import numpy as np
# Write code that slices the matrix below (items in red only)
matrix = np.array([[ 1, 2, 3, 4, 5],
                   [ 6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])
sliced_matrix = matrix[3:, :]
print(sliced_matrix)

[[16 17 18 19 20]
 [21 22 23 24 25]]
